name: Trigger auto deployment for cinema-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cinema-backend-AutoDeployTrigger-15768cb8-1332-4b71-a920-945e890f0d87.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CINEMABACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CINEMABACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CINEMABACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: cinemaacr6825.azurecr.io
          registryUsername: ${{ secrets.CINEMABACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CINEMABACKEND_REGISTRY_PASSWORD }}
          containerAppName: cinema-backend
          resourceGroup: cinema-rg
          imageToBuild: cinemaacr6825.azurecr.io/cinema-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


